//! Concept Bottleneck Model implementation for trading.

use crate::api::bybit::Kline;
use crate::models::concepts::{ConceptExtractor, TradingConcepts};
use serde::{Deserialize, Serialize};
use std::collections::HashMap;

/// Trading signal generated by the model.
#[derive(Debug, Clone, Copy, PartialEq, Serialize, Deserialize)]
pub enum TradingSignal {
    Buy,
    Sell,
    Hold,
}

/// Prediction result with explanation.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Prediction {
    pub signal: TradingSignal,
    pub confidence: f64,
    pub concepts: TradingConcepts,
    pub contributions: HashMap<String, f64>,
}

/// Task predictor that maps concepts to trading signals.
pub struct TaskPredictor {
    weights: Vec<Vec<f64>>,
    bias: Vec<f64>,
}

impl TaskPredictor {
    /// Create a new task predictor with default weights.
    pub fn new() -> Self {
        // Weights: [BUY, HOLD, SELL] x [11 concepts]
        // Concepts: trend_dir, trend_str, vol_regime, vol_val, mom_sig, mom_val,
        //           vol_prof, vol_ratio, rsi, support_dist, resist_dist
        let weights = vec![
            vec![0.3, 0.2, -0.1, -0.1, 0.2, 0.15, 0.1, 0.05, -0.1, 0.1, -0.1],  // BUY
            vec![0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],        // HOLD
            vec![-0.3, 0.2, 0.1, 0.1, -0.2, -0.15, -0.1, -0.05, 0.1, -0.1, 0.1], // SELL
        ];
        let bias = vec![0.0, 0.3, 0.0]; // Slight bias toward HOLD

        Self { weights, bias }
    }

    /// Predict trading signal from concept vector.
    pub fn predict(&self, concept_vector: &[f64]) -> (TradingSignal, f64) {
        let logits = self.forward(concept_vector);
        let probs = softmax(&logits);

        let (idx, &max_prob) = probs
            .iter()
            .enumerate()
            .max_by(|(_, a), (_, b)| a.partial_cmp(b).unwrap())
            .unwrap();

        let signal = match idx {
            0 => TradingSignal::Buy,
            1 => TradingSignal::Hold,
            _ => TradingSignal::Sell,
        };

        (signal, max_prob)
    }

    /// Compute logits for each action.
    fn forward(&self, concept_vector: &[f64]) -> Vec<f64> {
        self.weights
            .iter()
            .zip(&self.bias)
            .map(|(w, b)| {
                w.iter()
                    .zip(concept_vector)
                    .map(|(wi, ci)| wi * ci)
                    .sum::<f64>()
                    + b
            })
            .collect()
    }

    /// Get contribution of each concept to the prediction.
    pub fn get_contributions(&self, concept_vector: &[f64]) -> HashMap<String, f64> {
        let concept_names = vec![
            "trend_direction",
            "trend_strength",
            "volatility_regime",
            "volatility_value",
            "momentum_signal",
            "momentum_value",
            "volume_profile",
            "volume_ratio",
            "rsi",
            "support_distance",
            "resistance_distance",
        ];

        let logits = self.forward(concept_vector);
        let (idx, _) = logits
            .iter()
            .enumerate()
            .max_by(|(_, a), (_, b)| a.partial_cmp(b).unwrap())
            .unwrap();

        concept_names
            .into_iter()
            .enumerate()
            .map(|(i, name)| {
                (name.to_string(), self.weights[idx][i] * concept_vector[i])
            })
            .collect()
    }
}

impl Default for TaskPredictor {
    fn default() -> Self {
        Self::new()
    }
}

/// Complete Concept Bottleneck Model for trading.
pub struct ConceptBottleneckTrader {
    concept_extractor: ConceptExtractor,
    task_predictor: TaskPredictor,
}

impl ConceptBottleneckTrader {
    /// Create a new Concept Bottleneck Trader.
    pub fn new() -> Self {
        Self {
            concept_extractor: ConceptExtractor::new(),
            task_predictor: TaskPredictor::new(),
        }
    }

    /// Predict trading signal from market data.
    ///
    /// # Arguments
    ///
    /// * `klines` - Vector of OHLCV candlesticks
    ///
    /// # Returns
    ///
    /// Tuple of (TradingSignal, TradingConcepts) if successful.
    pub fn predict(&self, klines: &[Kline]) -> Option<(TradingSignal, TradingConcepts)> {
        let concepts = self.concept_extractor.extract(klines)?;
        let concept_vector = concepts.to_vector();
        let (signal, _) = self.task_predictor.predict(&concept_vector);
        Some((signal, concepts))
    }

    /// Predict with full explanation.
    pub fn predict_with_explanation(&self, klines: &[Kline]) -> Option<Prediction> {
        let concepts = self.concept_extractor.extract(klines)?;
        let concept_vector = concepts.to_vector();
        let (signal, confidence) = self.task_predictor.predict(&concept_vector);
        let contributions = self.task_predictor.get_contributions(&concept_vector);

        Some(Prediction {
            signal,
            confidence,
            concepts,
            contributions,
        })
    }

    /// Predict with concept intervention.
    ///
    /// Allows overriding specific concept values before making the final prediction.
    pub fn predict_with_intervention(
        &self,
        klines: &[Kline],
        overrides: &HashMap<String, f64>,
    ) -> Option<Prediction> {
        let concepts = self.concept_extractor.extract(klines)?;
        let mut concept_vector = concepts.to_vector();

        let concept_indices: HashMap<&str, usize> = [
            ("trend_direction", 0),
            ("trend_strength", 1),
            ("volatility_regime", 2),
            ("volatility_value", 3),
            ("momentum_signal", 4),
            ("momentum_value", 5),
            ("volume_profile", 6),
            ("volume_ratio", 7),
            ("rsi", 8),
            ("support_distance", 9),
            ("resistance_distance", 10),
        ]
        .into_iter()
        .collect();

        // Apply overrides
        for (name, value) in overrides {
            if let Some(&idx) = concept_indices.get(name.as_str()) {
                concept_vector[idx] = *value;
            }
        }

        let (signal, confidence) = self.task_predictor.predict(&concept_vector);
        let contributions = self.task_predictor.get_contributions(&concept_vector);

        Some(Prediction {
            signal,
            confidence,
            concepts,
            contributions,
        })
    }
}

impl Default for ConceptBottleneckTrader {
    fn default() -> Self {
        Self::new()
    }
}

/// Softmax function for converting logits to probabilities.
fn softmax(x: &[f64]) -> Vec<f64> {
    let max = x.iter().cloned().fold(f64::NEG_INFINITY, f64::max);
    let exp_sum: f64 = x.iter().map(|xi| (xi - max).exp()).sum();
    x.iter().map(|xi| (xi - max).exp() / exp_sum).collect()
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::api::bybit::generate_sample_klines;

    #[test]
    fn test_predict() {
        let model = ConceptBottleneckTrader::new();
        let klines = generate_sample_klines(100);

        let result = model.predict(&klines);
        assert!(result.is_some());

        let (signal, _concepts) = result.unwrap();
        assert!(matches!(
            signal,
            TradingSignal::Buy | TradingSignal::Sell | TradingSignal::Hold
        ));
    }

    #[test]
    fn test_predict_with_explanation() {
        let model = ConceptBottleneckTrader::new();
        let klines = generate_sample_klines(100);

        let prediction = model.predict_with_explanation(&klines);
        assert!(prediction.is_some());

        let pred = prediction.unwrap();
        assert!(pred.confidence >= 0.0 && pred.confidence <= 1.0);
        assert!(!pred.contributions.is_empty());
    }

    #[test]
    fn test_intervention() {
        let model = ConceptBottleneckTrader::new();
        let klines = generate_sample_klines(100);

        let mut overrides = HashMap::new();
        overrides.insert("trend_direction".to_string(), -1.0); // Force bearish

        let prediction = model.predict_with_intervention(&klines, &overrides);
        assert!(prediction.is_some());
    }

    #[test]
    fn test_softmax() {
        let logits = vec![1.0, 2.0, 3.0];
        let probs = softmax(&logits);

        // Probabilities should sum to 1
        let sum: f64 = probs.iter().sum();
        assert!((sum - 1.0).abs() < 1e-6);

        // All probabilities should be positive
        assert!(probs.iter().all(|&p| p > 0.0));
    }
}
