"""
Backtesting framework for QuantNet transfer trading strategies.

Provides:
- QuantNetBacktester: Backtest engine using QuantNet trading signals
- calculate_metrics: Comprehensive performance metric computation
"""

import torch
import numpy as np
import pandas as pd
from typing import Dict, List, Optional
import logging

from .quantnet_model import QuantNet

logger = logging.getLogger(__name__)


class QuantNetBacktester:
    """
    Backtesting framework for QuantNet transfer trading strategies.

    Evaluates asset-specific trading signals generated by the QuantNet model,
    applying configurable transaction costs and position management.

    Args:
        model: Trained QuantNet model
        transaction_cost: Cost per trade as a fraction (e.g., 0.001 = 10 bps)
        signal_threshold: Minimum absolute signal value to open a position
    """

    def __init__(
        self,
        model: QuantNet,
        transaction_cost: float = 0.001,
        signal_threshold: float = 0.0,
    ):
        self.model = model
        self.transaction_cost = transaction_cost
        self.signal_threshold = signal_threshold

    def backtest(
        self,
        prices: pd.Series,
        features: pd.DataFrame,
        asset: str,
        initial_capital: float = 10000.0,
    ) -> pd.DataFrame:
        """
        Run backtest on historical data for a specific asset.

        Args:
            prices: Price series aligned with features
            features: Feature DataFrame (columns matching model input)
            asset: Asset name (must match a trading head in the model)
            initial_capital: Starting capital

        Returns:
            DataFrame with columns: date, price, signal, position,
            position_return, capital
        """
        self.model.eval()
        feature_tensor = torch.FloatTensor(features.values)

        with torch.no_grad():
            z = self.model.encode(feature_tensor)
            signals = self.model.trading_heads[asset](z).numpy().flatten()

        results: List[Dict] = []
        capital = initial_capital
        position = 0.0

        for i in range(len(features) - 1):
            signal = float(signals[i])

            # Determine new position from signal
            if abs(signal) < self.signal_threshold:
                new_position = 0.0
            else:
                new_position = signal  # Continuous position sizing

            # Transaction cost on position change
            position_change = abs(new_position - position)
            if position_change > 1e-8:
                capital *= (1 - self.transaction_cost * position_change)

            # Actual return for the period
            actual_return = prices.iloc[i + 1] / prices.iloc[i] - 1
            position_return = position * actual_return
            capital *= (1 + position_return)

            results.append({
                "date": features.index[i],
                "price": prices.iloc[i],
                "signal": signal,
                "position": position,
                "position_return": position_return,
                "capital": capital,
            })

            position = new_position

        return pd.DataFrame(results)

    def backtest_multi_asset(
        self,
        asset_prices: Dict[str, pd.Series],
        asset_features: Dict[str, pd.DataFrame],
        initial_capital: float = 10000.0,
    ) -> Dict[str, pd.DataFrame]:
        """
        Run backtest across multiple assets.

        Args:
            asset_prices: Dict mapping asset name -> price series
            asset_features: Dict mapping asset name -> feature DataFrame
            initial_capital: Starting capital per asset

        Returns:
            Dict mapping asset name -> backtest results DataFrame
        """
        all_results: Dict[str, pd.DataFrame] = {}

        for asset in asset_prices:
            if asset not in self.model.trading_heads:
                logger.warning(
                    f"No trading head for '{asset}', skipping backtest."
                )
                continue
            if asset not in asset_features:
                logger.warning(
                    f"No features for '{asset}', skipping backtest."
                )
                continue

            try:
                results = self.backtest(
                    asset_prices[asset],
                    asset_features[asset],
                    asset,
                    initial_capital,
                )
                all_results[asset] = results
                logger.info(
                    f"Backtest for {asset}: "
                    f"final capital={results['capital'].iloc[-1]:.2f}"
                )
            except Exception as e:
                logger.error(f"Backtest failed for {asset}: {e}")

        return all_results


def calculate_metrics(results: pd.DataFrame) -> Dict[str, float]:
    """
    Calculate comprehensive trading performance metrics.

    Computes standard quantitative finance metrics from backtest results.

    Args:
        results: DataFrame from QuantNetBacktester.backtest()
            Required columns: position_return, capital

    Returns:
        Dict with the following metrics:
        - total_return: Cumulative return over the period
        - annualized_return: Annualized total return (252 trading days)
        - annualized_volatility: Annualized return volatility
        - sharpe_ratio: Annualized Sharpe ratio (risk-free rate = 0)
        - sortino_ratio: Annualized Sortino ratio (downside deviation)
        - max_drawdown: Maximum peak-to-trough drawdown
        - win_rate: Fraction of positive return periods
        - num_trades: Number of position changes
    """
    returns = results["position_return"]

    # Total return
    total_return = (
        results["capital"].iloc[-1] / results["capital"].iloc[0] - 1
    )

    # Annualized return (assuming 252 trading days)
    n_periods = max(len(results), 1)
    ann_return = (1 + total_return) ** (252 / n_periods) - 1

    # Annualized volatility
    ann_volatility = returns.std() * np.sqrt(252)

    # Sharpe ratio
    sharpe_ratio = (
        np.sqrt(252) * returns.mean() / (returns.std() + 1e-10)
    )

    # Sortino ratio (downside deviation only)
    downside_returns = returns[returns < 0]
    downside_std = downside_returns.std() if len(downside_returns) > 0 else 0.0
    sortino_ratio = (
        np.sqrt(252) * returns.mean() / (downside_std + 1e-10)
    )

    # Maximum drawdown
    cumulative = (1 + returns).cumprod()
    rolling_max = cumulative.expanding().max()
    max_drawdown = (cumulative / rolling_max - 1).min()

    # Win rate
    wins = (returns > 0).sum()
    losses_count = (returns < 0).sum()
    win_rate = (
        wins / (wins + losses_count) if (wins + losses_count) > 0 else 0.0
    )

    # Number of trades (position changes)
    num_trades = int((results["position"].diff().abs() > 1e-8).sum())

    return {
        "total_return": float(total_return),
        "annualized_return": float(ann_return),
        "annualized_volatility": float(ann_volatility),
        "sharpe_ratio": float(sharpe_ratio),
        "sortino_ratio": float(sortino_ratio),
        "max_drawdown": float(max_drawdown),
        "win_rate": float(win_rate),
        "num_trades": num_trades,
    }


def print_metrics(metrics: Dict[str, float]) -> None:
    """
    Pretty-print performance metrics.

    Args:
        metrics: Dict from calculate_metrics()
    """
    logger.info("=" * 50)
    logger.info("Trading Performance Metrics")
    logger.info("=" * 50)
    logger.info(f"  Total Return:      {metrics['total_return']:>10.4f}")
    logger.info(f"  Ann. Return:       {metrics['annualized_return']:>10.4f}")
    logger.info(f"  Ann. Volatility:   {metrics['annualized_volatility']:>10.4f}")
    logger.info(f"  Sharpe Ratio:      {metrics['sharpe_ratio']:>10.4f}")
    logger.info(f"  Sortino Ratio:     {metrics['sortino_ratio']:>10.4f}")
    logger.info(f"  Max Drawdown:      {metrics['max_drawdown']:>10.4f}")
    logger.info(f"  Win Rate:          {metrics['win_rate']:>10.4f}")
    logger.info(f"  Num Trades:        {metrics['num_trades']:>10d}")
    logger.info("=" * 50)


if __name__ == "__main__":
    logging.basicConfig(level=logging.INFO)

    # Demo with synthetic data
    np.random.seed(42)
    n = 300
    dates = pd.date_range("2023-01-01", periods=n, freq="h")
    prices = pd.Series(
        100 * np.exp(np.cumsum(np.random.randn(n) * 0.005)),
        index=dates,
    )

    from .data_loader import create_features

    df = pd.DataFrame({"close": prices}, index=dates)
    features = create_features(df)
    prices_aligned = prices.loc[features.index]

    asset_name = "BTCUSDT"
    model = QuantNet(
        input_size=features.shape[1],
        encoder_hidden=[64, 32, 16],
        head_hidden=32,
        asset_names=[asset_name],
    )

    backtester = QuantNetBacktester(
        model, transaction_cost=0.001, signal_threshold=0.1,
    )
    results = backtester.backtest(prices_aligned, features, asset_name)
    metrics = calculate_metrics(results)
    print_metrics(metrics)
