//! Trading signal types.

/// Direction of a trading signal.
#[derive(Debug, Clone, Copy, PartialEq)]
pub enum SignalDirection {
    /// Go long (buy)
    Long,
    /// Go short (sell)
    Short,
    /// No position
    Neutral,
}

/// A trading signal generated by the Gated SSM model.
#[derive(Debug, Clone)]
pub struct TradingSignal {
    /// Timestamp (milliseconds since epoch)
    pub timestamp: i64,
    /// Signal direction
    pub direction: SignalDirection,
    /// Confidence level (0.0 to 1.0)
    pub confidence: f64,
}

impl TradingSignal {
    /// Convert signal to a numeric position: 1.0, -1.0, or 0.0.
    pub fn to_position(&self) -> f64 {
        match self.direction {
            SignalDirection::Long => 1.0,
            SignalDirection::Short => -1.0,
            SignalDirection::Neutral => 0.0,
        }
    }
}
