//! Trading signal definitions and utilities.

use serde::{Deserialize, Serialize};

/// Trading signal generated by the S4 model.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum TradingSignal {
    /// Buy signal with confidence level.
    Buy { confidence: f64 },
    /// Hold signal with confidence level.
    Hold { confidence: f64 },
    /// Sell signal with confidence level.
    Sell { confidence: f64 },
}

impl TradingSignal {
    /// Get the confidence level of the signal.
    pub fn confidence(&self) -> f64 {
        match self {
            TradingSignal::Buy { confidence } => *confidence,
            TradingSignal::Hold { confidence } => *confidence,
            TradingSignal::Sell { confidence } => *confidence,
        }
    }

    /// Check if this is a buy signal.
    pub fn is_buy(&self) -> bool {
        matches!(self, TradingSignal::Buy { .. })
    }

    /// Check if this is a sell signal.
    pub fn is_sell(&self) -> bool {
        matches!(self, TradingSignal::Sell { .. })
    }

    /// Check if this is a hold signal.
    pub fn is_hold(&self) -> bool {
        matches!(self, TradingSignal::Hold { .. })
    }

    /// Get the position direction: 1 for buy, -1 for sell, 0 for hold.
    pub fn direction(&self) -> i32 {
        match self {
            TradingSignal::Buy { .. } => 1,
            TradingSignal::Sell { .. } => -1,
            TradingSignal::Hold { .. } => 0,
        }
    }

    /// Get position size based on confidence (0 to 1).
    pub fn position_size(&self, max_size: f64, min_confidence: f64) -> f64 {
        let conf = self.confidence();
        if conf < min_confidence {
            0.0
        } else {
            let scale = (conf - min_confidence) / (1.0 - min_confidence);
            self.direction() as f64 * max_size * scale
        }
    }

    /// Convert signal to string representation.
    pub fn to_string_with_confidence(&self) -> String {
        match self {
            TradingSignal::Buy { confidence } => {
                format!("BUY (confidence: {:.2}%)", confidence * 100.0)
            }
            TradingSignal::Hold { confidence } => {
                format!("HOLD (confidence: {:.2}%)", confidence * 100.0)
            }
            TradingSignal::Sell { confidence } => {
                format!("SELL (confidence: {:.2}%)", confidence * 100.0)
            }
        }
    }
}

impl std::fmt::Display for TradingSignal {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            TradingSignal::Buy { confidence } => write!(f, "BUY ({:.1}%)", confidence * 100.0),
            TradingSignal::Hold { confidence } => write!(f, "HOLD ({:.1}%)", confidence * 100.0),
            TradingSignal::Sell { confidence } => write!(f, "SELL ({:.1}%)", confidence * 100.0),
        }
    }
}

/// Signal strength categorization.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum SignalStrength {
    Strong,
    Moderate,
    Weak,
}

impl SignalStrength {
    /// Determine strength from confidence.
    pub fn from_confidence(confidence: f64) -> Self {
        if confidence >= 0.8 {
            SignalStrength::Strong
        } else if confidence >= 0.6 {
            SignalStrength::Moderate
        } else {
            SignalStrength::Weak
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_signal_confidence() {
        let signal = TradingSignal::Buy { confidence: 0.75 };
        assert_eq!(signal.confidence(), 0.75);
        assert!(signal.is_buy());
        assert!(!signal.is_sell());
    }

    #[test]
    fn test_signal_direction() {
        assert_eq!(TradingSignal::Buy { confidence: 0.5 }.direction(), 1);
        assert_eq!(TradingSignal::Sell { confidence: 0.5 }.direction(), -1);
        assert_eq!(TradingSignal::Hold { confidence: 0.5 }.direction(), 0);
    }

    #[test]
    fn test_position_size() {
        let signal = TradingSignal::Buy { confidence: 0.8 };
        let size = signal.position_size(1.0, 0.6);
        assert!(size > 0.0 && size <= 1.0);

        let weak_signal = TradingSignal::Buy { confidence: 0.5 };
        let size = weak_signal.position_size(1.0, 0.6);
        assert_eq!(size, 0.0);
    }
}
