//! Trading strategy using transfer learning predictions.
//!
//! Generates trading signals based on model predictions and applies
//! risk management rules including position sizing, stop-losses,
//! and confidence thresholds.

use ndarray::Array1;

/// Trading signal generated by the strategy.
#[derive(Debug, Clone, Copy, PartialEq)]
pub enum TradingSignal {
    /// Buy signal with confidence (0.0 to 1.0)
    Buy,
    /// Sell signal with confidence
    Sell,
    /// Hold / no action
    Hold,
}

impl TradingSignal {
    /// Create from class index (0=Down/Sell, 1=Hold, 2=Up/Buy).
    pub fn from_class(class: usize) -> Self {
        match class {
            0 => TradingSignal::Sell,
            2 => TradingSignal::Buy,
            _ => TradingSignal::Hold,
        }
    }
}

/// Current position state.
#[derive(Debug, Clone, Copy, PartialEq)]
pub enum Position {
    /// Long position with entry price and size
    Long { entry_price: f64, size: f64 },
    /// Short position with entry price and size
    Short { entry_price: f64, size: f64 },
    /// No position (flat)
    Flat,
}

/// Result of a completed trade.
#[derive(Debug, Clone)]
pub struct TradeResult {
    pub entry_price: f64,
    pub exit_price: f64,
    pub direction: TradingSignal,
    pub pnl: f64,
    pub pnl_pct: f64,
    pub holding_period: usize,
}

/// Transfer learning-based trading strategy.
///
/// Uses predictions from a transfer learning model to generate
/// trading signals with risk management controls.
#[derive(Debug, Clone)]
pub struct TransferTradingStrategy {
    /// Minimum confidence threshold for signals
    confidence_threshold: f64,
    /// Maximum position size as fraction of portfolio
    max_position_pct: f64,
    /// Stop-loss percentage
    stop_loss_pct: f64,
    /// Take-profit percentage
    take_profit_pct: f64,
    /// Maximum daily drawdown percentage
    max_daily_drawdown_pct: f64,
    /// Domain similarity threshold (below this, reduce position size)
    domain_similarity_threshold: f64,
    /// Current position
    position: Position,
    /// Trade history
    trades: Vec<TradeResult>,
    /// Current portfolio value
    portfolio_value: f64,
    /// Daily starting portfolio value
    daily_start_value: f64,
    /// Bars held in current position
    bars_held: usize,
}

impl TransferTradingStrategy {
    /// Create a new trading strategy with default risk parameters.
    pub fn new(initial_portfolio: f64) -> Self {
        Self {
            confidence_threshold: 0.65,
            max_position_pct: 0.02,
            stop_loss_pct: 0.015,
            take_profit_pct: 0.03,
            max_daily_drawdown_pct: 0.03,
            domain_similarity_threshold: 0.7,
            position: Position::Flat,
            trades: Vec::new(),
            portfolio_value: initial_portfolio,
            daily_start_value: initial_portfolio,
            bars_held: 0,
        }
    }

    /// Set the confidence threshold for generating signals.
    pub fn with_confidence_threshold(mut self, threshold: f64) -> Self {
        self.confidence_threshold = threshold;
        self
    }

    /// Set the maximum position size (fraction of portfolio).
    pub fn with_max_position(mut self, pct: f64) -> Self {
        self.max_position_pct = pct;
        self
    }

    /// Set the stop-loss percentage.
    pub fn with_stop_loss(mut self, pct: f64) -> Self {
        self.stop_loss_pct = pct;
        self
    }

    /// Set the take-profit percentage.
    pub fn with_take_profit(mut self, pct: f64) -> Self {
        self.take_profit_pct = pct;
        self
    }

    /// Generate a trading signal from model prediction probabilities.
    ///
    /// # Arguments
    /// * `proba` - Class probabilities [P(Down), P(Hold), P(Up)]
    /// * `current_price` - Current market price
    /// * `domain_similarity` - Similarity between source and target domains (0-1)
    pub fn generate_signal(
        &mut self,
        proba: &Array1<f64>,
        current_price: f64,
        domain_similarity: f64,
    ) -> TradingSignal {
        // Check daily drawdown limit
        if self.daily_drawdown() > self.max_daily_drawdown_pct {
            return self.close_position_signal(current_price);
        }

        // Check stop-loss and take-profit for existing positions
        if let Some(exit_signal) = self.check_exit_conditions(current_price) {
            self.close_position(current_price);
            return exit_signal;
        }

        // Get the predicted class and confidence
        let (class, confidence) = proba
            .iter()
            .enumerate()
            .max_by(|a, b| a.1.partial_cmp(b.1).unwrap())
            .map(|(i, &c)| (i, c))
            .unwrap_or((1, 0.0));

        // Apply confidence threshold
        if confidence < self.confidence_threshold {
            return TradingSignal::Hold;
        }

        // Reduce confidence for low domain similarity
        let adjusted_confidence = if domain_similarity < self.domain_similarity_threshold {
            confidence * domain_similarity
        } else {
            confidence
        };

        if adjusted_confidence < self.confidence_threshold {
            return TradingSignal::Hold;
        }

        let signal = TradingSignal::from_class(class);

        // Execute signal
        match (&self.position, signal) {
            (Position::Flat, TradingSignal::Buy) => {
                let size = self.calculate_position_size(domain_similarity);
                self.position = Position::Long {
                    entry_price: current_price,
                    size,
                };
                self.bars_held = 0;
                TradingSignal::Buy
            }
            (Position::Flat, TradingSignal::Sell) => {
                let size = self.calculate_position_size(domain_similarity);
                self.position = Position::Short {
                    entry_price: current_price,
                    size,
                };
                self.bars_held = 0;
                TradingSignal::Sell
            }
            (Position::Long { .. }, TradingSignal::Sell) => {
                self.close_position(current_price);
                TradingSignal::Sell
            }
            (Position::Short { .. }, TradingSignal::Buy) => {
                self.close_position(current_price);
                TradingSignal::Buy
            }
            _ => {
                self.bars_held += 1;
                TradingSignal::Hold
            }
        }
    }

    /// Check stop-loss and take-profit conditions.
    fn check_exit_conditions(&self, current_price: f64) -> Option<TradingSignal> {
        match self.position {
            Position::Long { entry_price, .. } => {
                let pnl_pct = (current_price - entry_price) / entry_price;
                if pnl_pct <= -self.stop_loss_pct {
                    Some(TradingSignal::Sell) // Stop-loss hit
                } else if pnl_pct >= self.take_profit_pct {
                    Some(TradingSignal::Sell) // Take-profit hit
                } else {
                    None
                }
            }
            Position::Short { entry_price, .. } => {
                let pnl_pct = (entry_price - current_price) / entry_price;
                if pnl_pct <= -self.stop_loss_pct {
                    Some(TradingSignal::Buy) // Stop-loss hit
                } else if pnl_pct >= self.take_profit_pct {
                    Some(TradingSignal::Buy) // Take-profit hit
                } else {
                    None
                }
            }
            Position::Flat => None,
        }
    }

    /// Close the current position at the given price.
    fn close_position(&mut self, exit_price: f64) {
        let trade = match self.position {
            Position::Long { entry_price, size } => {
                let pnl = (exit_price - entry_price) * size;
                let pnl_pct = (exit_price - entry_price) / entry_price;
                self.portfolio_value += pnl;
                Some(TradeResult {
                    entry_price,
                    exit_price,
                    direction: TradingSignal::Buy,
                    pnl,
                    pnl_pct,
                    holding_period: self.bars_held,
                })
            }
            Position::Short { entry_price, size } => {
                let pnl = (entry_price - exit_price) * size;
                let pnl_pct = (entry_price - exit_price) / entry_price;
                self.portfolio_value += pnl;
                Some(TradeResult {
                    entry_price,
                    exit_price,
                    direction: TradingSignal::Sell,
                    pnl,
                    pnl_pct,
                    holding_period: self.bars_held,
                })
            }
            Position::Flat => None,
        };

        if let Some(trade) = trade {
            self.trades.push(trade);
        }

        self.position = Position::Flat;
        self.bars_held = 0;
    }

    /// Generate a signal to close the current position.
    fn close_position_signal(&mut self, current_price: f64) -> TradingSignal {
        match self.position {
            Position::Long { .. } => {
                self.close_position(current_price);
                TradingSignal::Sell
            }
            Position::Short { .. } => {
                self.close_position(current_price);
                TradingSignal::Buy
            }
            Position::Flat => TradingSignal::Hold,
        }
    }

    /// Calculate position size based on risk parameters and domain similarity.
    fn calculate_position_size(&self, domain_similarity: f64) -> f64 {
        let base_size = self.portfolio_value * self.max_position_pct;

        // Reduce position size for low domain similarity
        if domain_similarity < self.domain_similarity_threshold {
            base_size * (domain_similarity / self.domain_similarity_threshold)
        } else {
            base_size
        }
    }

    /// Current daily drawdown as a fraction.
    fn daily_drawdown(&self) -> f64 {
        if self.daily_start_value == 0.0 {
            0.0
        } else {
            (self.daily_start_value - self.portfolio_value) / self.daily_start_value
        }
    }

    /// Reset the daily starting value (call at start of each trading day).
    pub fn reset_daily(&mut self) {
        self.daily_start_value = self.portfolio_value;
    }

    /// Get the current position.
    pub fn position(&self) -> &Position {
        &self.position
    }

    /// Get the trade history.
    pub fn trades(&self) -> &[TradeResult] {
        &self.trades
    }

    /// Get the current portfolio value.
    pub fn portfolio_value(&self) -> f64 {
        self.portfolio_value
    }

    /// Calculate strategy performance metrics.
    pub fn performance_summary(&self) -> PerformanceSummary {
        let total_trades = self.trades.len();
        let winning_trades = self.trades.iter().filter(|t| t.pnl > 0.0).count();
        let total_pnl: f64 = self.trades.iter().map(|t| t.pnl).sum();
        let gross_profit: f64 = self.trades.iter().filter(|t| t.pnl > 0.0).map(|t| t.pnl).sum();
        let gross_loss: f64 = self.trades.iter().filter(|t| t.pnl < 0.0).map(|t| t.pnl.abs()).sum();

        let win_rate = if total_trades > 0 {
            winning_trades as f64 / total_trades as f64
        } else {
            0.0
        };

        let profit_factor = if gross_loss > 0.0 {
            gross_profit / gross_loss
        } else if gross_profit > 0.0 {
            f64::INFINITY
        } else {
            0.0
        };

        let returns: Vec<f64> = self.trades.iter().map(|t| t.pnl_pct).collect();
        let avg_return = if returns.is_empty() {
            0.0
        } else {
            returns.iter().sum::<f64>() / returns.len() as f64
        };

        let return_std = if returns.len() < 2 {
            0.0
        } else {
            let variance = returns
                .iter()
                .map(|r| (r - avg_return).powi(2))
                .sum::<f64>()
                / (returns.len() - 1) as f64;
            variance.sqrt()
        };

        let sharpe_ratio = if return_std > 0.0 {
            avg_return / return_std * (252.0_f64).sqrt() // Annualized
        } else {
            0.0
        };

        let downside_returns: Vec<f64> = returns.iter().filter(|&&r| r < 0.0).copied().collect();
        let downside_std = if downside_returns.len() < 2 {
            0.0
        } else {
            let mean_down = downside_returns.iter().sum::<f64>() / downside_returns.len() as f64;
            let var = downside_returns
                .iter()
                .map(|r| (r - mean_down).powi(2))
                .sum::<f64>()
                / (downside_returns.len() - 1) as f64;
            var.sqrt()
        };

        let sortino_ratio = if downside_std > 0.0 {
            avg_return / downside_std * (252.0_f64).sqrt()
        } else {
            0.0
        };

        // Maximum drawdown
        let mut peak = 0.0_f64;
        let mut max_drawdown = 0.0_f64;
        let mut cumulative = 0.0;
        for trade in &self.trades {
            cumulative += trade.pnl;
            peak = peak.max(cumulative);
            let drawdown = if peak > 0.0 { (peak - cumulative) / peak } else { 0.0 };
            max_drawdown = max_drawdown.max(drawdown);
        }

        PerformanceSummary {
            total_trades,
            winning_trades,
            win_rate,
            total_pnl,
            profit_factor,
            sharpe_ratio,
            sortino_ratio,
            max_drawdown,
            avg_return,
        }
    }
}

/// Summary of strategy performance metrics.
#[derive(Debug, Clone)]
pub struct PerformanceSummary {
    pub total_trades: usize,
    pub winning_trades: usize,
    pub win_rate: f64,
    pub total_pnl: f64,
    pub profit_factor: f64,
    pub sharpe_ratio: f64,
    pub sortino_ratio: f64,
    pub max_drawdown: f64,
    pub avg_return: f64,
}

impl std::fmt::Display for PerformanceSummary {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        writeln!(f, "=== Performance Summary ===")?;
        writeln!(f, "Total Trades:    {}", self.total_trades)?;
        writeln!(f, "Winning Trades:  {}", self.winning_trades)?;
        writeln!(f, "Win Rate:        {:.2}%", self.win_rate * 100.0)?;
        writeln!(f, "Total PnL:       {:.2}", self.total_pnl)?;
        writeln!(f, "Profit Factor:   {:.2}", self.profit_factor)?;
        writeln!(f, "Sharpe Ratio:    {:.2}", self.sharpe_ratio)?;
        writeln!(f, "Sortino Ratio:   {:.2}", self.sortino_ratio)?;
        writeln!(f, "Max Drawdown:    {:.2}%", self.max_drawdown * 100.0)?;
        writeln!(f, "Avg Return:      {:.4}%", self.avg_return * 100.0)?;
        Ok(())
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use ndarray::Array1;

    #[test]
    fn test_trading_signal_from_class() {
        assert_eq!(TradingSignal::from_class(0), TradingSignal::Sell);
        assert_eq!(TradingSignal::from_class(1), TradingSignal::Hold);
        assert_eq!(TradingSignal::from_class(2), TradingSignal::Buy);
    }

    #[test]
    fn test_strategy_creation() {
        let strategy = TransferTradingStrategy::new(100_000.0);
        assert_eq!(strategy.portfolio_value(), 100_000.0);
        assert_eq!(strategy.position(), &Position::Flat);
        assert!(strategy.trades().is_empty());
    }

    #[test]
    fn test_buy_signal_generation() {
        let mut strategy = TransferTradingStrategy::new(100_000.0)
            .with_confidence_threshold(0.5);

        // High confidence Buy signal
        let proba = Array1::from_vec(vec![0.1, 0.2, 0.7]); // Up
        let signal = strategy.generate_signal(&proba, 100.0, 0.8);
        assert_eq!(signal, TradingSignal::Buy);
        assert!(matches!(strategy.position(), Position::Long { .. }));
    }

    #[test]
    fn test_sell_signal_generation() {
        let mut strategy = TransferTradingStrategy::new(100_000.0)
            .with_confidence_threshold(0.5);

        let proba = Array1::from_vec(vec![0.7, 0.2, 0.1]); // Down
        let signal = strategy.generate_signal(&proba, 100.0, 0.8);
        assert_eq!(signal, TradingSignal::Sell);
        assert!(matches!(strategy.position(), Position::Short { .. }));
    }

    #[test]
    fn test_hold_on_low_confidence() {
        let mut strategy = TransferTradingStrategy::new(100_000.0)
            .with_confidence_threshold(0.7);

        let proba = Array1::from_vec(vec![0.4, 0.3, 0.3]); // Low confidence
        let signal = strategy.generate_signal(&proba, 100.0, 0.8);
        assert_eq!(signal, TradingSignal::Hold);
        assert_eq!(strategy.position(), &Position::Flat);
    }

    #[test]
    fn test_reduced_position_low_similarity() {
        // Use two separate strategies to compare position sizes
        let mut strategy_high = TransferTradingStrategy::new(100_000.0)
            .with_confidence_threshold(0.3)
            .with_max_position(0.02);

        let mut strategy_low = TransferTradingStrategy::new(100_000.0)
            .with_confidence_threshold(0.3)
            .with_max_position(0.02);

        let proba = Array1::from_vec(vec![0.05, 0.05, 0.9]); // High confidence Buy

        // High similarity
        strategy_high.generate_signal(&proba, 100.0, 0.95);
        let high_sim_size = match *strategy_high.position() {
            Position::Long { size, .. } => size,
            _ => panic!("Expected long position for high similarity"),
        };

        // Low similarity
        strategy_low.generate_signal(&proba, 100.0, 0.5);
        let low_sim_size = match *strategy_low.position() {
            Position::Long { size, .. } => size,
            _ => panic!("Expected long position for low similarity"),
        };

        assert!(
            low_sim_size < high_sim_size,
            "Low similarity ({}) should produce smaller position than high similarity ({})",
            low_sim_size,
            high_sim_size,
        );
    }

    #[test]
    fn test_stop_loss() {
        let mut strategy = TransferTradingStrategy::new(100_000.0)
            .with_confidence_threshold(0.5)
            .with_stop_loss(0.02);

        // Open long position
        let proba = Array1::from_vec(vec![0.1, 0.2, 0.7]);
        strategy.generate_signal(&proba, 100.0, 0.8);

        // Price drops below stop-loss
        let hold_proba = Array1::from_vec(vec![0.3, 0.4, 0.3]);
        let signal = strategy.generate_signal(&hold_proba, 97.0, 0.8);
        assert_eq!(signal, TradingSignal::Sell); // Stop-loss triggered
        assert_eq!(strategy.position(), &Position::Flat);
    }

    #[test]
    fn test_performance_summary() {
        let mut strategy = TransferTradingStrategy::new(100_000.0)
            .with_confidence_threshold(0.5);

        // Execute some trades
        let buy_proba = Array1::from_vec(vec![0.1, 0.2, 0.7]);
        let sell_proba = Array1::from_vec(vec![0.7, 0.2, 0.1]);

        strategy.generate_signal(&buy_proba, 100.0, 0.8);
        strategy.generate_signal(&sell_proba, 105.0, 0.8); // Close with profit

        strategy.generate_signal(&buy_proba, 100.0, 0.8);
        strategy.generate_signal(&sell_proba, 98.0, 0.8); // Close with loss

        let summary = strategy.performance_summary();
        assert_eq!(summary.total_trades, 2);
        assert_eq!(summary.winning_trades, 1);
        assert!((summary.win_rate - 0.5).abs() < 1e-10);
    }
}
