//! Trading Utilities Module
//!
//! This module provides trading-related structures and utilities
//! for working with distilled decision tree models.

use serde::{Deserialize, Serialize};

/// Trading signal generated by models
#[derive(Debug, Clone, Copy, PartialEq, Serialize, Deserialize)]
pub enum TradingSignal {
    /// Strong buy signal
    StrongBuy,
    /// Buy signal
    Buy,
    /// Neutral/hold signal
    Hold,
    /// Sell signal
    Sell,
    /// Strong sell signal
    StrongSell,
}

impl TradingSignal {
    /// Create signal from prediction probability
    pub fn from_probability(prob: f64) -> Self {
        if prob > 0.8 {
            TradingSignal::StrongBuy
        } else if prob > 0.6 {
            TradingSignal::Buy
        } else if prob > 0.4 {
            TradingSignal::Hold
        } else if prob > 0.2 {
            TradingSignal::Sell
        } else {
            TradingSignal::StrongSell
        }
    }

    /// Get recommended position size multiplier
    pub fn position_multiplier(&self) -> f64 {
        match self {
            TradingSignal::StrongBuy => 1.0,
            TradingSignal::Buy => 0.75,
            TradingSignal::Hold => 0.0,
            TradingSignal::Sell => -0.75,
            TradingSignal::StrongSell => -1.0,
        }
    }

    /// Check if signal is bullish
    pub fn is_bullish(&self) -> bool {
        matches!(self, TradingSignal::StrongBuy | TradingSignal::Buy)
    }

    /// Check if signal is bearish
    pub fn is_bearish(&self) -> bool {
        matches!(self, TradingSignal::StrongSell | TradingSignal::Sell)
    }
}

impl std::fmt::Display for TradingSignal {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            TradingSignal::StrongBuy => write!(f, "STRONG BUY"),
            TradingSignal::Buy => write!(f, "BUY"),
            TradingSignal::Hold => write!(f, "HOLD"),
            TradingSignal::Sell => write!(f, "SELL"),
            TradingSignal::StrongSell => write!(f, "STRONG SELL"),
        }
    }
}

/// Current position state
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Position {
    /// Symbol/asset
    pub symbol: String,
    /// Position size (negative for short)
    pub size: f64,
    /// Entry price
    pub entry_price: f64,
    /// Current unrealized PnL
    pub unrealized_pnl: f64,
    /// Stop loss price
    pub stop_loss: Option<f64>,
    /// Take profit price
    pub take_profit: Option<f64>,
}

impl Position {
    /// Create a new position
    pub fn new(symbol: String, size: f64, entry_price: f64) -> Self {
        Self {
            symbol,
            size,
            entry_price,
            unrealized_pnl: 0.0,
            stop_loss: None,
            take_profit: None,
        }
    }

    /// Update position with current price
    pub fn update(&mut self, current_price: f64) {
        if self.size > 0.0 {
            self.unrealized_pnl = (current_price - self.entry_price) * self.size;
        } else {
            self.unrealized_pnl = (self.entry_price - current_price) * self.size.abs();
        }
    }

    /// Check if position is long
    pub fn is_long(&self) -> bool {
        self.size > 0.0
    }

    /// Check if position is short
    pub fn is_short(&self) -> bool {
        self.size < 0.0
    }

    /// Check if stop loss is triggered
    pub fn is_stop_triggered(&self, current_price: f64) -> bool {
        if let Some(stop) = self.stop_loss {
            if self.is_long() {
                current_price <= stop
            } else {
                current_price >= stop
            }
        } else {
            false
        }
    }

    /// Check if take profit is triggered
    pub fn is_take_profit_triggered(&self, current_price: f64) -> bool {
        if let Some(tp) = self.take_profit {
            if self.is_long() {
                current_price >= tp
            } else {
                current_price <= tp
            }
        } else {
            false
        }
    }

    /// Set stop loss based on ATR
    pub fn set_atr_stop(&mut self, atr: f64, multiplier: f64) {
        let stop_distance = atr * multiplier;
        self.stop_loss = Some(if self.is_long() {
            self.entry_price - stop_distance
        } else {
            self.entry_price + stop_distance
        });
    }

    /// Set take profit based on risk-reward ratio
    pub fn set_risk_reward_tp(&mut self, risk_reward_ratio: f64) {
        if let Some(stop) = self.stop_loss {
            let risk = (self.entry_price - stop).abs();
            let reward = risk * risk_reward_ratio;
            self.take_profit = Some(if self.is_long() {
                self.entry_price + reward
            } else {
                self.entry_price - reward
            });
        }
    }
}

/// Risk management parameters
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct RiskParams {
    /// Maximum position size as fraction of capital
    pub max_position_size: f64,
    /// Maximum number of concurrent positions
    pub max_positions: usize,
    /// Maximum loss per trade as fraction of capital
    pub max_loss_per_trade: f64,
    /// Maximum daily loss as fraction of capital
    pub max_daily_loss: f64,
    /// Minimum confidence threshold for trade
    pub min_confidence: f64,
}

impl Default for RiskParams {
    fn default() -> Self {
        Self {
            max_position_size: 0.1,
            max_positions: 5,
            max_loss_per_trade: 0.02,
            max_daily_loss: 0.05,
            min_confidence: 0.6,
        }
    }
}

impl RiskParams {
    /// Calculate position size based on risk parameters
    pub fn calculate_position_size(
        &self,
        capital: f64,
        entry_price: f64,
        stop_loss: f64,
    ) -> f64 {
        let risk_per_trade = capital * self.max_loss_per_trade;
        let price_risk = (entry_price - stop_loss).abs();

        if price_risk == 0.0 {
            return 0.0;
        }

        let size_by_risk = risk_per_trade / price_risk;
        let max_size = (capital * self.max_position_size) / entry_price;

        size_by_risk.min(max_size)
    }

    /// Check if trade meets risk criteria
    pub fn validate_trade(&self, confidence: f64, current_positions: usize) -> bool {
        confidence >= self.min_confidence && current_positions < self.max_positions
    }
}

/// Trading rule extracted from distilled tree
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TradingRule {
    /// Rule conditions as human-readable string
    pub conditions: String,
    /// Trading signal
    pub signal: TradingSignal,
    /// Historical win rate
    pub win_rate: f64,
    /// Historical average return
    pub avg_return: f64,
    /// Number of historical occurrences
    pub occurrences: usize,
}

impl TradingRule {
    /// Create a new trading rule
    pub fn new(conditions: String, signal: TradingSignal) -> Self {
        Self {
            conditions,
            signal,
            win_rate: 0.0,
            avg_return: 0.0,
            occurrences: 0,
        }
    }

    /// Update rule statistics with new outcome
    pub fn update_stats(&mut self, return_pct: f64) {
        let n = self.occurrences as f64;
        let new_n = n + 1.0;

        // Update win rate
        let is_win = return_pct > 0.0;
        self.win_rate = (self.win_rate * n + if is_win { 1.0 } else { 0.0 }) / new_n;

        // Update average return
        self.avg_return = (self.avg_return * n + return_pct) / new_n;

        self.occurrences += 1;
    }

    /// Get expected value of the rule
    pub fn expected_value(&self) -> f64 {
        self.win_rate * self.avg_return.abs() - (1.0 - self.win_rate) * self.avg_return.abs()
    }
}

impl std::fmt::Display for TradingRule {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(
            f,
            "IF {} THEN {} (WR: {:.1}%, AvgRet: {:.2}%, N={})",
            self.conditions,
            self.signal,
            self.win_rate * 100.0,
            self.avg_return * 100.0,
            self.occurrences
        )
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_trading_signal() {
        assert_eq!(TradingSignal::from_probability(0.9), TradingSignal::StrongBuy);
        assert_eq!(TradingSignal::from_probability(0.65), TradingSignal::Buy);
        assert_eq!(TradingSignal::from_probability(0.5), TradingSignal::Hold);
        assert_eq!(TradingSignal::from_probability(0.3), TradingSignal::Sell);
        assert_eq!(TradingSignal::from_probability(0.1), TradingSignal::StrongSell);
    }

    #[test]
    fn test_position() {
        let mut pos = Position::new("BTCUSDT".to_string(), 1.0, 50000.0);
        pos.update(51000.0);
        assert_eq!(pos.unrealized_pnl, 1000.0);

        pos.set_atr_stop(1000.0, 2.0);
        assert_eq!(pos.stop_loss, Some(48000.0));
    }

    #[test]
    fn test_risk_params() {
        let params = RiskParams::default();
        let size = params.calculate_position_size(100000.0, 50000.0, 48000.0);
        assert!(size > 0.0);
        assert!(size <= 100000.0 * params.max_position_size / 50000.0);
    }
}
